language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - latest

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install --no-interaction --prefer-source

script:
  - ant phplint
  - ant phpcs
  - ant phpunit
